// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2LiCpYNYKxlrDTXS5q9OsfQDp_Zq3ZM',
    appId: '1:979151294493:web:2c32870c48b7d64020f6f4',
    messagingSenderId: '979151294493',
    projectId: 'proplay-eac23',
    authDomain: 'proplay-eac23.firebaseapp.com',
    storageBucket: 'proplay-eac23.firebasestorage.app',
    measurementId: 'G-9EZXVJYLKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZY0zvn5s0I2Eh5aEGy06QelTsC2SeUYg',
    appId: '1:979151294493:android:77cd123ece3d7e3d20f6f4',
    messagingSenderId: '979151294493',
    projectId: 'proplay-eac23',
    storageBucket: 'proplay-eac23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTO2hGJLMHgHUgIzO0MN_DJmexpvku43E',
    appId: '1:979151294493:ios:c5726f00d72b9f8320f6f4',
    messagingSenderId: '979151294493',
    projectId: 'proplay-eac23',
    storageBucket: 'proplay-eac23.firebasestorage.app',
    iosBundleId: 'com.example.proplay',
  );
}
