List<Map<String, dynamic>> preferences = [
  {
    "additional_info": "",
    "auto_return": "approved",
    "back_urls": {
      "failure": "proplay://failure",
      "pending": "proplay://pending",
      "success": "proplay://success",
    },
    "binary_mode": false,
    "client_id": "7513148469170824",
    "collector_id": 127411672,
    "coupon_code": null,
    "coupon_labels": null,
    "date_created": "2026-03-03T16:46:18.225-04:00",
    "date_of_expiration": null,
    "expiration_date_from": null,
    "expiration_date_to": null,
    "expires": false,
    "external_reference": "",
    "id": "127411672-499ce7a6-9d86-486c-9f17-618874092664",
    "init_point":
        "https://www.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-499ce7a6-9d86-486c-9f17-618874092664",
    "internal_metadata": null,
    "items": [
      {
        "id": "",
        "category_id": "",
        "currency_id": "PEN",
        "description": "",
        "title": "15 pro coins",
        "quantity": 1,
        "unit_price": 17,
      },
    ],
    "marketplace": "MP-MKT-7513148469170824",
    "marketplace_fee": 0,
    "metadata": {},
    "notification_url": null,
    "operation_type": "regular_payment",
    "payer": {
      "phone": {"area_code": "", "number": ""},
      "address": {"zip_code": "", "street_name": "", "street_number": null},
      "email": "",
      "identification": {"number": "", "type": ""},
      "name": "",
      "surname": "",
      "date_created": null,
      "last_purchase": null,
    },
    "payment_methods": {
      "default_card_id": null,
      "default_payment_method_id": null,
      "excluded_payment_methods": [
        {"id": ""},
      ],
      "excluded_payment_types": [
        {"id": ""},
      ],
      "installments": null,
      "default_installments": null,
    },
    "processing_modes": null,
    "product_id": null,
    "preference_expired": false,
    "redirect_urls": {"failure": "", "pending": "", "success": ""},
    "sandbox_init_point":
        "https://sandbox.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-499ce7a6-9d86-486c-9f17-618874092664",
    "site_id": "MPE",
    "shipments": {
      "default_shipping_method": null,
      "receiver_address": {
        "zip_code": "",
        "street_name": "",
        "street_number": null,
        "floor": "",
        "apartment": "",
        "city_name": null,
        "state_name": null,
        "country_name": null,
        "neighborhood": null,
      },
    },
    "total_amount": null,
    "last_updated": null,
    "financing_group": "",
  },
  {
    "additional_info": "",
    "auto_return": "approved",
    "back_urls": {
      "failure": "proplay://failure",
      "pending": "proplay://pending",
      "success": "proplay://success",
    },
    "binary_mode": false,
    "client_id": "7513148469170824",
    "collector_id": 127411672,
    "coupon_code": null,
    "coupon_labels": null,
    "date_created": "2026-03-03T16:46:18.677-04:00",
    "date_of_expiration": null,
    "expiration_date_from": null,
    "expiration_date_to": null,
    "expires": false,
    "external_reference": "",
    "id": "127411672-ad8c065e-604c-4b02-b589-94e3ca8cf0c7",
    "init_point":
        "https://www.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-ad8c065e-604c-4b02-b589-94e3ca8cf0c7",
    "internal_metadata": null,
    "items": [
      {
        "id": "",
        "category_id": "",
        "currency_id": "PEN",
        "description": "",
        "title": "25 pro coins",
        "quantity": 1,
        "unit_price": 28,
      },
    ],
    "marketplace": "MP-MKT-7513148469170824",
    "marketplace_fee": 0,
    "metadata": {},
    "notification_url": null,
    "operation_type": "regular_payment",
    "payer": {
      "phone": {"area_code": "", "number": ""},
      "address": {"zip_code": "", "street_name": "", "street_number": null},
      "email": "",
      "identification": {"number": "", "type": ""},
      "name": "",
      "surname": "",
      "date_created": null,
      "last_purchase": null,
    },
    "payment_methods": {
      "default_card_id": null,
      "default_payment_method_id": null,
      "excluded_payment_methods": [
        {"id": ""},
      ],
      "excluded_payment_types": [
        {"id": ""},
      ],
      "installments": null,
      "default_installments": null,
    },
    "processing_modes": null,
    "product_id": null,
    "preference_expired": false,
    "redirect_urls": {"failure": "", "pending": "", "success": ""},
    "sandbox_init_point":
        "https://sandbox.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-ad8c065e-604c-4b02-b589-94e3ca8cf0c7",
    "site_id": "MPE",
    "shipments": {
      "default_shipping_method": null,
      "receiver_address": {
        "zip_code": "",
        "street_name": "",
        "street_number": null,
        "floor": "",
        "apartment": "",
        "city_name": null,
        "state_name": null,
        "country_name": null,
        "neighborhood": null,
      },
    },
    "total_amount": null,
    "last_updated": null,
    "financing_group": "",
  },
  {
    "additional_info": "",
    "auto_return": "approved",
    "back_urls": {
      "failure": "proplay://failure",
      "pending": "proplay://pending",
      "success": "proplay://success",
    },
    "binary_mode": false,
    "client_id": "7513148469170824",
    "collector_id": 127411672,
    "coupon_code": null,
    "coupon_labels": null,
    "date_created": "2026-03-03T16:46:19.082-04:00",
    "date_of_expiration": null,
    "expiration_date_from": null,
    "expiration_date_to": null,
    "expires": false,
    "external_reference": "",
    "id": "127411672-c9544eb8-a6d8-4d02-bdb6-77439c033254",
    "init_point":
        "https://www.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-c9544eb8-a6d8-4d02-bdb6-77439c033254",
    "internal_metadata": null,
    "items": [
      {
        "id": "",
        "category_id": "",
        "currency_id": "PEN",
        "description": "",
        "title": "50 pro coins",
        "quantity": 1,
        "unit_price": 55,
      },
    ],
    "marketplace": "MP-MKT-7513148469170824",
    "marketplace_fee": 0,
    "metadata": {},
    "notification_url": null,
    "operation_type": "regular_payment",
    "payer": {
      "phone": {"area_code": "", "number": ""},
      "address": {"zip_code": "", "street_name": "", "street_number": null},
      "email": "",
      "identification": {"number": "", "type": ""},
      "name": "",
      "surname": "",
      "date_created": null,
      "last_purchase": null,
    },
    "payment_methods": {
      "default_card_id": null,
      "default_payment_method_id": null,
      "excluded_payment_methods": [
        {"id": ""},
      ],
      "excluded_payment_types": [
        {"id": ""},
      ],
      "installments": null,
      "default_installments": null,
    },
    "processing_modes": null,
    "product_id": null,
    "preference_expired": false,
    "redirect_urls": {"failure": "", "pending": "", "success": ""},
    "sandbox_init_point":
        "https://sandbox.mercadopago.com.pe/checkout/v1/redirect?pref_id=127411672-c9544eb8-a6d8-4d02-bdb6-77439c033254",
    "site_id": "MPE",
    "shipments": {
      "default_shipping_method": null,
      "receiver_address": {
        "zip_code": "",
        "street_name": "",
        "street_number": null,
        "floor": "",
        "apartment": "",
        "city_name": null,
        "state_name": null,
        "country_name": null,
        "neighborhood": null,
      },
    },
    "total_amount": null,
    "last_updated": null,
    "financing_group": "",
  },
];
